version: '3.8'

services:
  rbac:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rbac
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
    environment:
      - DB_HOST=rbac-db
      - DB_NAME=auth_service
      - DB_USER=user
      - DB_PASSWORD=password
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
      - APP_ENV=dev
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      rbac-db:
        condition: service_healthy
      rbac-redis:
        condition: service_started
    networks:
      - app-network

  rbac-nginx:
    image: nginx:alpine
    container_name: rbac-nginx
    ports:
      - "8081:80"
    volumes:
      - ./web:/var/www/web:ro,cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/logs:/var/log/nginx:cached
    depends_on:
      - rbac
    networks:
      - app-network

  rbac-db:
    image: postgres:15
    container_name: rbac-db
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - rbac_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth_service"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  rbac-redis:
    image: redis:alpine
    container_name: rbac-redis
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  rbac_postgres_data: